### PR TITLE
Indicate that we forbid unsafe code

### PR DESCRIPTION
**Pull request by notgull**
Makes this show up as clean on `cargo-geiger`

### CODE REVIEW

**Comment by notgull** [comment]
@Soveu Any chance you could review this?

**Comment by Soveu** [comment]
Huh, why I haven't noticed that earlier? :eyes: 

I think we could change the version to 0.1.1 in the same PR.

**Comment by notgull** [comment]
> I think we could change the version to 0.1.1 in the same PR.

Sounds good! I bumped to v0.1.1 in Cargo.toml.

**Comment by Soveu** [comment]
Bumped it to 0.1.1 on crates.io :)

**Pull request merged**
